name: Analysing with MM-GBSA
category: analysis
authors: ""
shortdesc: This course walks through the process of perfprming a basic MM-GBSA analysis of a molecular dynamics simulation of a protein-ligand complex to estimate the ligand binding free energy.
longdesc: ""
